name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install "pipenv<=2022.8.5"
          pipenv sync --dev

      - name: Run tests
        run: pipenv run test

      - name: Check coding standards
        run: pipenv run lint
