name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: Debug
        run: |
          pipenv --version
          pipenv graph | grep certifi
          cat /home/runner/.local/share/virtualenvs/json-schema-viewer-xZjdKPGg/lib/python3.9/site-packages/certifi/__init__.py

      - name: Run tests
        run: pipenv run test

      - name: Check coding standards
        run: pipenv run lint
