name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install "pipenv==2024.4.0"
          pipenv sync --dev

      - name: Run tests
        run: pipenv run test

      - name: Check coding standards
        run: pipenv run lint
