name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv==2022.8.13

      - name: Install dependencies
        run: pipenv sync --dev --verbose

      - name: Debug
        run: |
          pipenv --version
          pipenv graph | grep certifi
          pipenv run pip list

      - name: Run tests
        run: pipenv run test

      - name: Check coding standards
        run: pipenv run lint
